@startuml turnos
' En un diagrama UML, las relaciones entre las clases a menudo se representan con líneas de asociación, por lo que no es necesario duplicar esta información en las listas dentro de las clases.
package "DTO - entidades" #AED6F1 {



skinparam shadowing true
    class Departamento {
        - int PK_id
        - String nombre
    }

    class Trabajador {
        - int PK_id
        - String nombre
        - int FK_departamentoId
    }
    class Turno {
        - int PK_id
        - String nombre
        - Time Inicio
        - Time Fin
    }
    class Posicion {
        - int PK_id
        - String nombre
        - int FK_departamentoId
    }

    class Ausencia {
        - String motivo
        - Date PK_inicio
        - Date PK_fin
        - int PK/FK_trabajadorId
    }

    class Asignacion << (C, Orchid) >>{
        - LocalDate fecha
        - int FK_trabajadorId
        - int FK_turnoId
        - int FK_posicionId
    }
    class Inactividad {
        - int PK_id
        - String descripcion
        - int FK_trabajadorId
    }


}

package "Negocio" #85C1E9 {
    class GestorTurnos {
        - DepartamentoDAO departamentoDAO
        - TrabajadorDAO trabajadorDAO
        - PosicionDAO posicionDAO
        - TurnoDAO turnoDAO
        - AusenciaDAO ausenciaDAO
        - InactividadDAO inactividadDAO
        + agregar()
        + eliminar()
        + modificar()
        + obtenerTodos()
        + obtenerPorId()
    }
}

package "DAO - persistencia" #3498DB {
    class DepartamentoDAO {}
    class TrabajadorDAO {}
    class PosicionDAO {}
    class TurnoDAO {}
    class AusenciaDAO {}
    class InactividadDAO {}
}

package "UI" #3498DB {
    class TurnosGUI {
        - GestorTurnos gestorTurnos
    }
}

Departamento "1" -- "*" Trabajador : contiene >
Departamento "1" -- "*" Posicion : gestiona >
Trabajador "n" -- "1" Departamento : pertenece a >
Trabajador -down-> "*" Ausencia : tiene >
Trabajador -down-> "*" Inactividad : tiene >
Trabajador -down-> "*" Asignacion : "está en" >
Turno -down-> "*" Asignacion : "incluye" >
Posicion -down-> "*" Asignacion : "cubre" >

GestorTurnos -down-> DepartamentoDAO : usa >
GestorTurnos -down-> TrabajadorDAO : usa >
GestorTurnos -down-> PosicionDAO : usa >
GestorTurnos -down-> TurnoDAO : usa >
GestorTurnos -down-> AusenciaDAO : usa >
GestorTurnos -down-> InactividadDAO : usa >

DepartamentoDAO -down-> Departamento : maneja >
TrabajadorDAO -down-> Trabajador : maneja >
PosicionDAO -down-> Posicion : maneja >
TurnoDAO -down-> Turno : maneja >
AusenciaDAO -down-> Ausencia : maneja >
InactividadDAO -down-> Inactividad : maneja >

TurnosGUI -down-> GestorTurnos : usa >

note right of GestorTurnos
    GestorTurnos usa todos los DAOs
    para manejar los DTOs correspondientes.
end note

@enduml